### ISSUE TITLE
Feature Request:  View current state

### ISSUE THREAD

**Issue by MikeBishop** [jason0x43/hubitat#3]
Just got this working.  It appears that I can see whether the fan is auto or not, and I can see that the thermostat is in heat-cool mode, but I don't see that this exposes the current state (heating, cooling, fanOnly, etc.).

The rules that I'm trying to port from WebCore to Rule Manager tie the state and speed of my ceiling fan to the thermostat's state.  Am I missing where this is exposed, or is this a request for new data?

**Comment by jason0x43** [comment]
As of commit 57ac3744, the Nest driver now reports the current state and current temperature.
